### ISSUE TITLE
Understand and create a plan for the state pattern

### ISSUE THREAD

**Issue by lastmjs** [alexandergunnarson/islander-monad#61]

**Comment by alexandergunnarson** [comment]
What's our plan for this? I'm not in the loop if we have one haha

**Comment by lastmjs** [comment]
I closed it because I'm beginning to understand and have a plan almost, and I still have the issue open for writing about it. I'll write it up in the doc

**Comment by alexandergunnarson** [comment]
Okay, sounds good!
