### ISSUE TITLE
Create a sequence diagram for what the program will do when a road is placed

### ISSUE THREAD

**Issue by lastmjs** [alexandergunnarson/islander-monad#70]
Create a sequence diagram that shows in detail what your program will do when a player places a road. Start the diagram at the point where the user clicks to place the road, and end the diagram by showing how the GUI gets updated to display the newly placed road.

**Comment by xaves** [comment]
I've got most of the flow done. I need a little help around the `http.post()`, `MoveReducers.buildRoad` (server side), and then updating the UI.

**Comment by xaves** [comment]
Finished it up! See the final thing [here](https://drive.google.com/file/d/0B7b1vAix0m99SUd3Q0xIME9EWjg/view?usp=sharing).
