### ISSUE TITLE
Join game should save the currentPlayerId to the Client State

### ISSUE THREAD

**Issue by Redge-Ballard** [alexandergunnarson/islander-monad#87]
We need the currentPlayerId for a lot of our can do methods. This id is only available when a player actually joins a game, so at that point we should save that client's player id into the client state so we can use it in our controllers.

**Comment by xaves** [comment]
I don't think that this is the responsibility of the JoinGameController. The client model has a list of players and each player has both a `playerID` and a `playerIndex` field. If other people need that data then I think they should either grab it from there, or save themselves a local copy. Either way I don't think it's the join game controller's responsibility.
