### ISSUE TITLE
How to display errors to the client

### ISSUE THREAD

**Issue by lastmjs** [alexandergunnarson/islander-monad#92]
When errors occur in the operations, we want to throw them up to the controllers. We need to decide on a nice way to them display the message to the user.

**Comment by alexandergunnarson** [comment]
Well, we can just have a modal that describes the error in a non-technical way, right?

**Comment by intcreator** [comment]
For debugging purposes, we might want to keep the technical errors.  However, once everything's solid I'm all for "A bad thing happened" client error messages.

**Comment by lastmjs** [comment]
Yes, we just need to make the modal and hook it up and stuff. Sometimes we'll need to display a targeted and descriptive message, which we'll define at the source of the error I suppose.

**Comment by lastmjs** [comment]
I think the login controller has an error message modal. If we need it it's there.

**Comment by lastmjs** [comment]
How do we do punctuation in our error messages? Should everything be a complete sentence?
