### ISSUE TITLE
Setup ant correctly with host and port parameters

### ISSUE THREAD

**Issue by lastmjs** [alexandergunnarson/islander-monad#94]
We aren't doing this correctly currently. From the spec:

> Create command line parameters on your client for both the host and port on which the
> Catan server is running. Modify the ant target “our-client” to support passing these
> parameters into the target with the names “host” and “port” respectively. You should be
> able to specify the host and port with either ANT or using the java command as specified
> below. 
> 
> Create a zip file containing the binaries (not source) for your Catan client, and send it to
> your testing team. The ANT target named make-tester-zip creates a file named
> tester.zip in the project’s root directory. If you have added new files or directories
> that your client needs to run, you may need to modify the make-tester-zip target to
> include them in the zip file. Test your zip file on Windows and Linux to ensure that it
> works correctly. After unzipping your zip file, testers should be able to run your Catan
> client by entering the following command: java -jar catan-client.jar <host>
> <port>

**Comment by alexandergunnarson** [comment]
So there are at least four kinds of builds in the ant.xml currently:

1) `ant test`, which compiles all the code and runs all server and client tests
2) `ant demo-*` (where `*` means either client or server), which runs the demo/provided client or server
3) `ant run-*`, which compiles all the non-test code and runs our client|server
4) `ant our-*`, which compiles all the non-test code, packages the client|server up into a .jar, and runs the .jar

I haven't tested out 4) yet, and we need to be able to make the `tester.zip` file work, as well as the host and port arguments.
